### ISSUE TITLE
Trouble..

### ISSUE THREAD

**Issue by heqtow** [iwotastic/order-tron#1]
**Order Tron is not working as before
I am getting an error like this:**

_Thank You In Advance.._

> Traceback (most recent call last):
>   File "/doc/home/Documents/Jobs/ETSY/development/etsy-api/order-tron-master/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/doc/home/Documents/Jobs/ETSY/development/etsy-api/order-tron-master/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
>     response = self.handle_exception(e)
>   File "/doc/home/Documents/Jobs/ETSY/development/etsy-api/order-tron-master/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
>     reraise(exc_type, exc_value, tb)
> 
>   File "/doc/home/Documents/Jobs/ETSY/development/etsy-api/order-tron-master/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/doc/home/Documents/Jobs/ETSY/development/etsy-api/order-tron-master/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/doc/home/Documents/Jobs/ETSY/development/etsy-api/order-tron-master/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/doc/home/Documents/Jobs/ETSY/development/etsy-api/order-tron-master/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/doc/home/Documents/Jobs/ETSY/development/etsy-api/order-tron-master/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/doc/home/Documents/Jobs/ETSY/development/etsy-api/order-tron-master/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/doc/home/Documents/Jobs/ETSY/development/etsy-api/order-tron-master/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/doc/home/Documents/Jobs/ETSY/development/etsy-api/order-tron-master/authenticated.py", line 34, in home
>     user_data = session.user_profile()
>   File "/doc/home/Documents/Jobs/ETSY/development/etsy-api/order-tron-master/session.py", line 53, in user_profile
>     self._user_data = resp.json()["results"][0]
> KeyError: 'results'

**Comment by iwotastic** [comment]
Hi heqtow, Order-tron is currently non-functional as a result of Etsy's recent deprecation of API v2.

I am a college student and am currently busy with coursework and whatnot, but since my parents use it for their business (this is actually why I created Order-tron), I will try and upgrade Order-tron to be compatible with API v3 once my semester is over.

On a side note: I find it really cool how someone (you) found and started using my side-project for a real use-case, so I have all the more reason to try and get it working.

**Comment by iwotastic** [comment]
Hey @heqtow, I apologize for the delay in responding to this issue.

Upon further research about the changes in v3 of Etsy's API, I have unfortunately discovered that Order-tron now exists in a grey area as far as the policy changes associated with the new API version. As such, I am afraid that I will have to make the choice to archive the Order-tron repo. You are free to continue using Order-tron as-is for assistance in creating your own solution, but I will no longer be updating it.
